# backtraces_path = "/path/to/neovide_backtraces.log" # see below for the default platform specific location
# fork = false
# frame = "full"
# idle = true
# maximized = false
# mouse-cursor-icon = "arrow"
# neovim-bin = "/usr/bin/nvim" # in reality found dynamically on $PATH if unset
# no-multigrid = false
# srgb = false
# tabs = true
# theme = "auto"
# title-hidden = true
# vsync = true
# wsl = false

[font]
size = 10
hinting = "none" # full/none/normal/slight
edging = "antialias"

[[font.normal]]
# family = "FiraCode Nerd Font"
family = "Maple Mono NF CN"
style = "W400"

# You can set a different font for fallback
[[font.normal]]
family = "等距更纱黑体 SC Nerd Font"
style = "Normal"

# [[font.bold]]
# family = "JetBrainsMono Nerd Font Propo"
# style = "W600"

# No need to specify fallback in every variant, if omitted or specified here
# but not found, it will fallback to normal font with this weight which is bold
# in this case.
# [[font.bold]]
# family = "Noto Sans CJK SC"
# style = "Bold"

[[font.italic]]
family = "Maple Mono NF CN"
# family = "VictorMono Nerd Font"
